[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "numpy",
    "h5py",
]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
omit = [
    "l0learn/src/*",
    "src/*",
]