# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

L0LearnFit <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, Tol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_L0Learn_L0LearnFit', PACKAGE = 'L0Learn', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, Tol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

L0LearnCV <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, Tol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_L0Learn_L0LearnCV', PACKAGE = 'L0Learn', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, Tol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

R_matrix_column_get_dense <- function(mat, col) {
    .Call('_L0Learn_R_matrix_column_get_dense', PACKAGE = 'L0Learn', mat, col)
}

R_matrix_column_get_sparse <- function(mat, col) {
    .Call('_L0Learn_R_matrix_column_get_sparse', PACKAGE = 'L0Learn', mat, col)
}

R_matrix_rows_get_dense <- function(mat, rows) {
    .Call('_L0Learn_R_matrix_rows_get_dense', PACKAGE = 'L0Learn', mat, rows)
}

R_matrix_rows_get_sparse <- function(mat, rows) {
    .Call('_L0Learn_R_matrix_rows_get_sparse', PACKAGE = 'L0Learn', mat, rows)
}

R_matrix_vector_schur_product_dense <- function(mat, u) {
    .Call('_L0Learn_R_matrix_vector_schur_product_dense', PACKAGE = 'L0Learn', mat, u)
}

R_matrix_vector_schur_product_sparse <- function(mat, u) {
    .Call('_L0Learn_R_matrix_vector_schur_product_sparse', PACKAGE = 'L0Learn', mat, u)
}

R_matrix_vector_divide_dense <- function(mat, u) {
    .Call('_L0Learn_R_matrix_vector_divide_dense', PACKAGE = 'L0Learn', mat, u)
}

R_matrix_vector_divide_sparse <- function(mat, u) {
    .Call('_L0Learn_R_matrix_vector_divide_sparse', PACKAGE = 'L0Learn', mat, u)
}

R_matrix_column_sums_dense <- function(mat) {
    .Call('_L0Learn_R_matrix_column_sums_dense', PACKAGE = 'L0Learn', mat)
}

R_matrix_column_sums_sparse <- function(mat) {
    .Call('_L0Learn_R_matrix_column_sums_sparse', PACKAGE = 'L0Learn', mat)
}

R_matrix_column_dot_dense <- function(mat, col, u) {
    .Call('_L0Learn_R_matrix_column_dot_dense', PACKAGE = 'L0Learn', mat, col, u)
}

R_matrix_column_dot_sparse <- function(mat, col, u) {
    .Call('_L0Learn_R_matrix_column_dot_sparse', PACKAGE = 'L0Learn', mat, col, u)
}

R_matrix_column_mult_dense <- function(mat, col, u) {
    .Call('_L0Learn_R_matrix_column_mult_dense', PACKAGE = 'L0Learn', mat, col, u)
}

R_matrix_column_mult_sparse <- function(mat, col, u) {
    .Call('_L0Learn_R_matrix_column_mult_sparse', PACKAGE = 'L0Learn', mat, col, u)
}

R_matrix_normalize_dense <- function(mat_norm) {
    .Call('_L0Learn_R_matrix_normalize_dense', PACKAGE = 'L0Learn', mat_norm)
}

R_matrix_normalize_sparse <- function(mat_norm) {
    .Call('_L0Learn_R_matrix_normalize_sparse', PACKAGE = 'L0Learn', mat_norm)
}

R_matrix_center_dense <- function(mat, intercept) {
    .Call('_L0Learn_R_matrix_center_dense', PACKAGE = 'L0Learn', mat, intercept)
}

R_matrix_center_sparse <- function(mat, intercept) {
    .Call('_L0Learn_R_matrix_center_sparse', PACKAGE = 'L0Learn', mat, intercept)
}

