name: Python CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - "python/**"
      - '.github/workflows/python.yml'

  pull_request:
    branches: [ master ]
    paths:
      - "python/**"
      - '.github/workflows/python.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']
        include:
          - os: macos-latest
          - os: ubuntu-latest
            INSTALL_DEPS: |
              sudo apt-get install -y liblapack-dev
              bash scripts/install_linux_libs.sh
    defaults:
      run:
        working-directory: ./python

    steps:
      - name: Checkout l0learn
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install-dependencies
        run: ${{ matrix.INSTALL_DEPS }}

      - name: Install L0Learn
        run: |
          python -m pip install --upgrade pip
          pip install .

  coverage:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    steps:
      - name: Checkout l0learn
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: install-dependencies
        run: |
          sudo apt-get install -y liblapack-dev
          bash scripts/install_linux_libs.sh

      - name: Install L0Learn
        run: |
          pip install .
      
      - name: Run Tests and Coverage
        run: |
          pip install pytest-cov coveralls hypothesis
          pytest tests/ --cov=l0learn
      
      - name: Coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

